// ---------------------------------------------------------------------------
// Microsoft Copilot Studio integration wrapper.
//
// Thin shim over the autogenerated `MicrosoftCopilotStudioService` (which
// `pac code add-data-source -a shared_microsoftcopilotstudio` produces — and
// which the @microsoft/power-apps-vite plugin will also regenerate on build
// whenever `power.config.json` lists the connector). Centralises:
//   - the configured agent name
//   - the placeholder `notificationUrl` that the connector body expects
//   - threading `conversationId` through to preserve multi-turn state
//   - normalising the documented response casing variants
//     (conversationId / ConversationId / conversationID)
//   - opportunistic JSON parsing of `responses[0]` so callers can read
//     structured agent payloads without each one duplicating the try/catch.
//
// Heads up: the public learn.microsoft.com doc for code-app + Copilot Studio
// shows an *object-shaped* signature:
//   ExecuteCopilotAsyncV2({ message, notificationUrl, agentName })
// The connector schema currently delivered to this tenant is positional:
//   ExecuteCopilotAsyncV2(Copilot, body, x_ms_conversation_id?, environmentId?)
// where `Copilot` is the URL path segment (== the agent name) and `body`
// carries the JSON `{ message, notificationUrl, ... }`. This wrapper hides
// that difference so callers can stay on the simpler logical model.
//
// The generated method is also typed `Promise<IOperationResult<void>>`,
// but at runtime the SDK still hands back the response body on
// `result.data`. We type-cast through `unknown` so the wrapper can read it.
//
// Setup steps:
//   1. Publish your Copilot Studio agent.
//   2. Find / create the MCS connection:
//        pac connection list                         # look for shared_microsoftcopilotstudio
//   3. Add the connector to the code app from PP-CoE-CodeApp/:
//        pac code add-data-source -a "shared_microsoftcopilotstudio" -c <connectionId>
//      (or: just keep the connectionReferences entry in power.config.json
//      pointing at a real GUID — the Vite plugin regenerates the rest.)
//   4. Set AGENT_NAME below to the {agentName} segment from the agent's
//      Channels > Web app URL (case-sensitive, includes publisher prefix).
//   5. Replace the TODO connectionId key in power.config.json.
//
// Reference:
//   https://learn.microsoft.com/en-us/power-apps/developer/code-apps/how-to/connect-to-copilot-studio
// ---------------------------------------------------------------------------

import { MicrosoftCopilotStudioService } from "../generated/services/MicrosoftCopilotStudioService";

// Configured agent name from Copilot Studio > Channels > Web app URL.
// Case-sensitive; includes publisher prefix.
export const AGENT_NAME = "msftcsa_PPCoEAgent";

// The connector body requires a notificationUrl but ignores its value in
// synchronous mode. The learn doc prescribes this exact placeholder string.
const NOTIFICATION_URL_PLACEHOLDER = "https://notificationurlplaceholder";

export interface SendMessageOptions {
  // Optional override so callers (e.g., AgentDetail) can route to a
  // record-specific agent without touching the global default.
  agentName?: string;
  // Pass the previous reply's `conversationId` to keep the agent in the
  // same dialog. Omit on the first turn — the connector will allocate one.
  conversationId?: string;
}

export interface CopilotStudioRawResponse {
  responses?: string[];
  lastResponse?: string;
  completed?: boolean;
  // Response casing isn't stable across server versions per the doc's
  // troubleshooting section; we collapse all three into `conversationId`.
  conversationId?: string;
  ConversationId?: string;
  conversationID?: string;
}

export interface CopilotStudioReply {
  // Best-effort plain-text reply: lastResponse if present, else last item
  // of responses[], else "".
  text: string;
  // If responses[0] looked like a JSON document, this holds the parsed
  // value. Otherwise undefined.
  parsed?: unknown;
  // Normalised conversation id (any of the three documented casings).
  conversationId?: string;
  completed: boolean;
  raw: CopilotStudioRawResponse;
}

function isAgentConfigured(name: string): boolean {
  return Boolean(name) && !name.startsWith("TODO-");
}

function pickConversationId(raw: CopilotStudioRawResponse): string | undefined {
  return raw.conversationId ?? raw.ConversationId ?? raw.conversationID;
}

function maybeParseJson(value: string | undefined): unknown {
  if (!value) return undefined;
  const trimmed = value.trim();
  // Cheap heuristic — only attempt parse if it looks like JSON.
  if (!trimmed.startsWith("{") && !trimmed.startsWith("[")) return undefined;
  try {
    return JSON.parse(trimmed);
  } catch {
    return undefined;
  }
}

function buildReply(raw: CopilotStudioRawResponse): CopilotStudioReply {
  const responses = raw.responses ?? [];
  const text = raw.lastResponse ?? responses[responses.length - 1] ?? "";
  return {
    text,
    parsed: maybeParseJson(responses[0]),
    conversationId: pickConversationId(raw),
    completed: raw.completed ?? true,
    raw,
  };
}

/**
 * Send a single message to the configured Copilot Studio agent and return
 * its reply. The connector's `ExecuteCopilotAsyncV2` action blocks until
 * the agent finishes, so this resolves with the full response.
 *
 * Pass `options.conversationId` (taken from a previous reply) to continue
 * the same conversation rather than starting a fresh one.
 *
 * Throws a setup error if AGENT_NAME is still the TODO placeholder.
 */
export async function sendMessage(
  message: string,
  options: SendMessageOptions = {},
): Promise<CopilotStudioReply> {
  const agentName = options.agentName ?? AGENT_NAME;
  if (!isAgentConfigured(agentName)) {
    throw new Error(
      "Copilot Studio agent is not configured yet. Set AGENT_NAME in " +
        "src/services/copilotStudio.ts to your published agent name. " +
        "See docs/copilot-studio-integration.md for the full setup walkthrough.",
    );
  }

  const result = await MicrosoftCopilotStudioService.ExecuteCopilotAsyncV2(
    agentName,
    {
      message,
      notificationUrl: NOTIFICATION_URL_PLACEHOLDER,
    },
    options.conversationId,
  );

  if (result?.success === false) {
    const errMsg = result.error
      ? typeof result.error === "string"
        ? result.error
        : result.error instanceof Error
          ? result.error.message
          : JSON.stringify(result.error)
      : "Unknown connector error";
    throw new Error(`Copilot Studio call failed: ${errMsg}`);
  }

  // The generated method is typed `Promise<IOperationResult<void>>` because
  // the connector swagger declares no 201 body, but the SDK passes the
  // actual response object through on `result.data` at runtime.
  const raw = (result?.data ?? {}) as unknown as CopilotStudioRawResponse;
  return buildReply(raw);
}
