import type { CuratedProperty } from "./types";

const ADDED_IN = "2026-09-09";
const SOURCE = "copilot-agents-dataverse" as const;

/** Cheap Inventory API fields used to prune agents before Dataverse calls. */
export const CURATED_AGENT_CANDIDATES: CuratedProperty[] = [
  {
    id: "candidateIsCliAgent",
    label: "CLI agent",
    path: "isCLIAgent",
    group: "Agent type",
    filter: { kind: "boolean" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "candidateSchemaName",
    label: "Schema name",
    path: "schemaName",
    group: "Identity",
    filter: { kind: "string" },
    source: SOURCE,
    addedIn: ADDED_IN,
    helpText:
      "Use starts with msdyn_ to include Microsoft first-party agents, or combine with not equals when reviewing a known publisher.",
  },
  {
    id: "candidateModel",
    label: "Inventory model",
    path: "model",
    group: "Behavior",
    filter: { kind: "string" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "candidateOrchestration",
    label: "Inventory orchestration",
    path: "orchestration",
    group: "Behavior",
    filter: { kind: "string" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "candidateAuthentication",
    label: "Inventory authentication",
    path: "authentication",
    group: "Security",
    filter: { kind: "string" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "candidateManaged",
    label: "Managed agent",
    path: "isManaged",
    group: "Governance",
    filter: { kind: "boolean" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "candidateOwner",
    label: "Owner ID",
    path: "ownerId",
    group: "Identity",
    filter: { kind: "string" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
];

/** Friendly Dataverse-backed evidence fields for Copilot Studio agents. */
export const CURATED_COPILOT_AGENTS: CuratedProperty[] = [
  {
    id: "memoryEnabled",
    label: "Memory enabled",
    path: "capabilities.memoryEnabled",
    group: "Detected capabilities",
    filter: { kind: "boolean" },
    source: SOURCE,
    addedIn: ADDED_IN,
    helpText:
      "Detected from bot.configuration.agentSettings.enableMemory. The app reports the setting without classifying its release status.",
  },
  {
    id: "externalTrigger",
    label: "External trigger present",
    path: "capabilities.externalTrigger",
    group: "Detected capabilities",
    filter: { kind: "boolean" },
    source: SOURCE,
    addedIn: ADDED_IN,
    helpText:
      "Detected only from parsed botcomponent data with kind ExternalTriggerConfiguration. Component type is retained as evidence but is not treated as proof.",
  },
  {
    id: "recurrenceTrigger",
    label: "Recurrence trigger present",
    path: "capabilities.recurrenceTrigger",
    group: "Detected capabilities",
    filter: { kind: "boolean" },
    source: SOURCE,
    addedIn: ADDED_IN,
    helpText:
      "Detected when an ExternalTriggerConfiguration uses AgentRecurrenceTrigger.",
  },
  {
    id: "configurationMemory",
    label: "Configuration: enable memory",
    path: "configuration.agentSettings.enableMemory",
    group: "Bot configuration",
    filter: { kind: "boolean" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "componentCount",
    label: "Component count",
    path: "components.componentCount",
    group: "Components",
    filter: { kind: "number" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "componentType",
    label: "Component type",
    path: "components.types",
    group: "Components",
    filter: { kind: "number" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "componentKind",
    label: "Parsed component kind",
    path: "components.kinds",
    group: "Components",
    filter: { kind: "string" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "componentName",
    label: "Component name",
    path: "components.names",
    group: "Components",
    filter: { kind: "string" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "componentSchemaName",
    label: "Component schema name",
    path: "components.schemaNames",
    group: "Components",
    filter: { kind: "string" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "externalTriggerSourceKind",
    label: "External trigger source kind",
    path: "components.any.externalTriggerSource.kind",
    group: "Components",
    filter: { kind: "string" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "botAuthenticationMode",
    label: "Dataverse authentication mode",
    path: "bot.authenticationmode",
    group: "Bot record",
    filter: { kind: "string" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "botManaged",
    label: "Dataverse managed state",
    path: "bot.ismanaged",
    group: "Bot record",
    filter: { kind: "boolean" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "botModifiedOn",
    label: "Dataverse modified date",
    path: "bot.modifiedon",
    group: "Bot record",
    filter: { kind: "date" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
  {
    id: "diagnosticsPresent",
    label: "Evidence parse issues",
    path: "diagnostics.hasIssues",
    group: "Diagnostics",
    filter: { kind: "boolean" },
    source: SOURCE,
    addedIn: ADDED_IN,
    helpText:
      "True when configuration JSON or component YAML could not be fully parsed. Inspect the raw result before treating a missing capability as definitive.",
  },
  {
    id: "diagnosticCount",
    label: "Evidence issue count",
    path: "diagnostics.count",
    group: "Diagnostics",
    filter: { kind: "number" },
    source: SOURCE,
    addedIn: ADDED_IN,
  },
];
