/**
 * Thin wrapper around the auto-generated `PPLicensingAPI_Wrapper_FlowService.Run`.
 *
 * Why this exists:
 *  1. The flow's PowerApp V2 trigger inputs are named `text` (the HTTP
 *     method) and `text_1` (the URL). These names are auto-generated by
 *     Power Automate and CANNOT be renamed — only the user-facing
 *     "Method" / "URL" titles can. Calling the generated service
 *     directly with `Run({ text, text_1 })` is a bug magnet (you'd
 *     swap them and not notice). This wrapper exposes the proper names.
 *  2. The flow returns `{ response: stringifiedJson }` — we JSON.parse
 *     it here so callers get typed data.
 *  3. The flow can fail in several ways (rejected promise, `success:false`,
 *     `success:true` with non-JSON body, empty body, JSON error envelope).
 *     We normalize all of them into a single `LicensingResult<T>` shape.
 *  4. In-flight dedupe — two simultaneous identical calls collapse into
 *     one flow invocation. Mirrors `spnEnrichment.ts`'s pattern.
 */

import { PPLicensingAPI_Wrapper_FlowService } from "../../generated/services/PPLicensingAPI_Wrapper_FlowService";
import type { LicensingResult } from "./types";

/**
 * Run shape at runtime. The generated `Run` returns
 * `IOperationResult<ResponseActionOutput>` where `ResponseActionOutput`
 * is `{ response?: string }`. `success` and `error` come from the
 * `IOperationResult` envelope — declared loosely here because the SDK
 * sometimes attaches stringly-typed error payloads.
 */
interface RunResult {
  success: boolean;
  data?: { response?: string };
  error?: unknown;
}

/** Module-level in-flight map. Keyed by stringified request to merge dupes. */
const inflight = new Map<string, Promise<LicensingResult<unknown>>>();

/** Reset hook for tests and for an eventual "Refresh" UI affordance. */
export function clearLicensingInflight(): void {
  inflight.clear();
}

export interface LicensingRequest {
  method: "GET";
  url: string;
}

/**
 * Invoke the licensing wrapper flow and return the parsed JSON body.
 *
 * Failure modes mapped to `{ ok: false, error }`:
 *  - flow promise rejects
 *  - `success: false` (with or without an `error` payload)
 *  - `success: true` but `data` or `data.response` is missing/empty
 *  - `response` isn't valid JSON (likely an HTML error page from the licensing API)
 *  - parsed JSON looks like an error envelope (`{ error: { message } }` or `{ message }` + `{ statusCode >= 400 }`)
 */
export async function callLicensing(
  req: LicensingRequest,
): Promise<LicensingResult<unknown>> {
  const key = `${req.method} ${req.url}`;
  const existing = inflight.get(key);
  if (existing) return existing;

  const p = invokeOnce(req).finally(() => {
    inflight.delete(key);
  });
  inflight.set(key, p);
  return p;
}

async function invokeOnce(req: LicensingRequest): Promise<LicensingResult<unknown>> {
  let raw: RunResult;
  try {
    // Translate ergonomic names → generated PowerApp V2 trigger names.
    // text  = HTTP method, text_1 = URL. See file header for why.
    raw = (await PPLicensingAPI_Wrapper_FlowService.Run({
      text: req.method,
      text_1: req.url,
    })) as unknown as RunResult;
  } catch (e) {
    return { ok: false, error: formatError(e) };
  }

  if (!raw.success) {
    return { ok: false, error: formatError(raw.error) || "Licensing flow returned success=false" };
  }

  const responseText = raw.data?.response;
  if (typeof responseText !== "string" || responseText.length === 0) {
    return { ok: false, error: "Empty response from licensing flow" };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(responseText);
  } catch {
    // The flow has no internal error handling, so a 4xx/5xx from the
    // licensing API often returns as an HTML error page in `response`.
    // Surface a short preview so the user can tell what went wrong.
    const preview = responseText.slice(0, 200).replace(/\s+/g, " ").trim();
    return { ok: false, error: `Non-JSON response from licensing API: ${preview}` };
  }

  const errEnvelope = detectErrorEnvelope(parsed);
  if (errEnvelope) return { ok: false, error: errEnvelope };

  return { ok: true, data: parsed };
}

/** Detect common JSON error shapes the licensing API or Azure APIM might return. */
function detectErrorEnvelope(parsed: unknown): string | null {
  if (!parsed || typeof parsed !== "object") return null;
  const obj = parsed as Record<string, unknown>;
  const status = obj.statusCode;
  const isHttpError = typeof status === "number" && status >= 400;
  const errorField = obj.error;
  if (errorField && typeof errorField === "object") {
    const msg = (errorField as { message?: unknown }).message;
    if (typeof msg === "string" && msg.length > 0) return msg;
    const code = (errorField as { code?: unknown }).code;
    if (typeof code === "string") return `Licensing API error: ${code}`;
  }
  if (typeof obj.message === "string" && isHttpError) {
    return `HTTP ${status}: ${obj.message}`;
  }
  if (isHttpError) return `HTTP ${status} from licensing API`;
  return null;
}

function formatError(e: unknown): string {
  if (!e) return "";
  if (e instanceof Error) return e.message;
  if (typeof e === "string") return e;
  if (typeof e === "object") {
    const obj = e as { message?: unknown };
    if (typeof obj.message === "string") return obj.message;
    try {
      return JSON.stringify(e);
    } catch {
      return String(e);
    }
  }
  return String(e);
}
